### ISSUE TITLE
users file

### ISSUE THREAD

**Issue by tortfeaser** [HausnerR/esphome-door-lock#1]
Hi mate, thanks for the effort with this.

I've mocked it up (and ordered PCBs, so hope I can get this going!)

I've got a file rfid_users at /config/www/ on Home Assistant. And I call the esphome.rfid_lock_1_sync_users_list_from_server service with data {"url":"https://hassio.local:8123/local/rfid_users"}

I know the file is available there, if I use the same URL in a browser the file is downloaded.

But calling the service results in an error in the console:

[18:46:27][D][rfid:165]: Fetching users list from server...
[18:46:27][E][rfid:174]: Invalid server response. Server unavailable?

Any ideas?

**Comment by tortfeaser** [comment]
OK, I've uploaded the rfid_users file to another webserver I have that isn't SSL, and that works. Is there a way I can call the service and have the ESP device download from the https link?

**Comment by HausnerR** [comment]
Hey,
It's possible but requires different approach to fetch data (use of different lib and code) and I'm not sure it would work with self-signed certificates.
For now there is no support for SSL and I have no plans to add it. Sorry
