### ISSUE TITLE
GPIO Definition

### ISSUE THREAD

**Issue by HFsi** [HausnerR/esphome-door-lock#2]
Hi!
Where do you define the GPIOs?
So I can adapt to a NodeMCU.
Thanks

**Comment by Haringstad** [comment]
Yes, I would like to know too ;-) Makes life a bit simpler.

**Comment by babichjacob** [comment]
From looking over the code to try to use this myself as well:
The two GPIOs needed for the RC522 are defined [here](https://github.com/HausnerR/esphome-door-lock/blob/master/door_lock_rfid.h#L188).
The initializer they're passed into is [here](https://github.com/miguelbalboa/rfid/blob/master/src/MFRC522.cpp#L250). 
So it looks like `chipSelectPin` is `D8` and `resetPowerDownPin` is `D3`.

Could anyone using the project share a wiring diagram or picture to show all the connections between the (MF)RC522 and the ESP board?

**Comment by drthanwho** [comment]
Hey from looking at the PCB design:

3.3V -> 3.3V
GND -> GND
MISO -> D6
MOSI -> D7
SCK -> D5
SDA -> D8

Since the same pins also exist on the nodemcu I just left the code the same though
