### ISSUE TITLE
Error: 'KeyValuePair' is not a member of 'esphome :: api'

### ISSUE THREAD

**Issue by malarconfresno** [HausnerR/esphome-door-lock#4]
Hello,

I am trying to use a nodeMCU + RC522.
When I try to compile and upload in esphome, I get the following error:
src / door_lock_rfid.h: 34: 12: error: 'KeyValuePair' is not a member of 'esphome :: api'

Any ideas?
Thank you

**Comment by stefkoch09** [comment]
Same problem here. In an older version of ESPHome it compiled fine. I guess the code in "door_lock_rfid.h" needs an update.

**Comment by HausnerR** [comment]
Hey, I fixed code, now it works with newest ESPhome
