### ISSUE TITLE
Feature Request: Last tag refresh if possible

### ISSUE THREAD

**Issue by bluefoxlee** [HausnerR/esphome-door-lock#5]
First of all, Really Thanks for the hard word. I just found this and flash it yesterday. it works so great, Thanks!

I did not use esphome-door-lock as a door lock but just a trigger for automation in Home Assistant. however, I found the last tag ID and description will remain unchanged until it read other tag or card. 

So wonder is it possible to make the code to resend the id and description ever time when tag to RFID.

**Comment by bluefoxlee** [comment]
Please ignore. Use reset_command to solved the issue. Thanks ^^

**Comment by HarryJHolmes** [comment]
Would you mind sharing where you find or include this reset_command? @bluefoxlee thanks

**Comment by bluefoxlee** [comment]
@Harryjholmes I am using the NFC reader with Home Assistant, so I mean the rest_command from Home Assistant instead of esphome itself.
