### ISSUE TITLE
ESPHome Update failed

### ISSUE THREAD

**Issue by BartEngelen** [HausnerR/esphome-door-lock#6]
Hello,
When I want to update my ESPHome project it fails all the time.
Is there a way to fix this ?
You can find the log in attachment.
Kind regards,
Bart
[logs_rfid-reader-terrein-8_upload (1).txt](https://github.com/HausnerR/esphome-door-lock/files/9818927/logs_rfid-reader-terrein-8_upload.1.txt)

**Comment by AshrafMikhael** [comment]
Hi
I got the same error. but after  remove or comment  "ESP8266HTTPClient" under libraries section of yaml, the compilation and installation completed successfully.

  libraries:
  #- "ESP8266HTTPClient"
  - "SPI"
  - "MFRC522"

**Comment by BartEngelen** [comment]
Hello,
Thanks this solved my problem.
Kind regards,
Bart Engelen
